.github/ISSUE_TEMPLATE/02-bug.yaml, .github/ISSUE_TEMPLATE/03-starter.yaml, .github/ISSUE_TEMPLATE/04-tooling.yaml, .github/ISSUE_TEMPLATE/05-documentation.yaml, docusaurus.config.js, src/pages/starters/index.tsx, src/pages/starters/styles.module.css, src/theme/Card/index.tsx
Adds an initial https://learningtypescript.com/starters with four projects. Also fixes a few issue template link typos, heh.
I'll push-to-main the right URL for the button once I can get the autogenerated URL from GitHub...
=> ✨ feat: added /starters page

docusaurus.config.js
Fixes the edit URL to be a join on the `main` branch -> `projects/` plus the computed `docsPath`.
=> 🐛: fix editUrl for docs (projects)

src/theme/NotFound/index.tsx, src/theme/NotFound/styles.module.css
Swizzles the `NotFound` component per https://github.com/facebook/docusaurus/discussions/6030 -> https://docusaurus.io/docs/swizzling#swizzling-theme-components.
=> ✨ feat: added custom 404 page

docusaurus.config.js
Breadcrumbs aren't very customizeable yet (#6953), so in the meantime this just removes them. Ah well.
=> 🐛 fix: remove faulty breadcrumbs

src/pages/projects/index.tsx, src/pages/projects/styles.module.css
Removes a no-longer-useful, now-harmful override.
=> 🐛 fix: horizontal padding on Projects page

src/theme/Footer/styles.module.css
Fixes up the flex alignment for the footer icons to be horizontal on mobile.
=> 🐛 fix: footer icon alignments

src/css/custom.css
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
=> fix: increase dark mode text contrast

src/theme/NavbarItem/DropdownLinkItem/styles.module.css
Hides the dropdown with `visibility: hidden` when not focused or hovered.
=> fix: remove Books dropdown visibility when hidden

docusaurus.config.js
The issue is that the `external-project-links.js` Remark plugin is running after the default Docusaurus ones. It should be in a `beforeDefaultRemarkPlugins` entry in `docusaurus.config.js.
=> fix: plugin order for Markdown copy button

docusaurus.config.js
Makes the shiki preset apply before all the normal classic preset stuff. Similar fix to #98.
=> Fix: move docusaurus-preset-shiki-twoslash before classic preset

package.json, src/css/custom.css, src/theme/CodeBlock/index.tsx, src/theme/CodeBlock/styles.module.css, yarn.lock
Swizzles the [`CodeBlock` component](https://docusaurus.io/docs/markdown-features/code-blocks#usage-in-jsx) and gives it styles roughly equivalent to the shiki ones.
Also bumps a bunch of versions to their latest. Just in case it's useful.
I know I should file an issue somewhere to not have to do this... but I just don't have the energy.
=> fix: align manual CodeBlock styles to shiki's

src/content/articles/why-increase-your-tsconfig-target.mdx
I've been using ES2021 for most of my configs, but have seen all sorts of targets in the wild. This article explains:
* The benefits of using a relatively recent `compilerOptions.target`
* How to choose a target
=> Article: Why Increase Your TSConfig `target`

docusaurus.config.js
Seen in the `.d.ts` types. https://docusaurus.io/docs/blog#blog-sidebar
=> fix: show all blogs in sidebar

src/content/articles/the-satisfies-operator.mdx
This PR fixes a broken link on the page: `Update the-satisfies-operator.mdx`.
Changes link from: `http://localhost:3000` to `https://www.learningtypescript.com`.
=> Fix broken link in: Update the-satisfies-operator.mdx

src/content/articles/narrowing-function-parameters-with-rests-and-tuples.mdx
I've seen this come up once in a while: that there are several strategies for declaring functions that may be called in multiple different ways. This article goes over three of the most reasonable ways:
1. Function overloads
2. Generic functions
3. Destructured rest parameters of a tuple type
=> Article: Narrowing Function Parameters With Rests And Tuples

src/css/custom.css, src/theme/CodeBlock/index.tsx
As promised... 😄 
Closes #117
Before:
After:
=> fix: Shiki twoslash error displays are visually offset slightly

src/pages/projects/index.tsx
It looks like the `code-container` div is injected from `twoslash`,
since we render the code block manually, the code isn't nested inside a code-container div (which is padded).
Seems like it happened due to the changes in #122
Closes #126 ✅
=> fix: missing padding in projects code block

src/content/articles/why-typescript-doesnt-include-a-throws-keyword.mdx
Adds the article covering why the throw types seem nice, all the blockers to having them in JS/TS, and some preferred alternatives.
=> feat: article 'Why TypeScript Doesn't Include a `throws` Keyword'

src/content/articles/why-increase-your-tsconfig-target.mdx
kangax compatibility table
links to a 404 github page
i think the correct page has moved to
https://compat-table.github.io/compat-table/es2016plus/
=> replace 404 link with working link for compat table

.github/ISSUE_TEMPLATE/config.yml, src/content/articles/branded-types.mdx, src/content/articles/extreme-explorations-of-typescripts-type-system.mdx, src/content/articles/narrowing-function-parameters-with-rests-and-tuples.mdx, src/content/articles/objects-functions-and-type-narrowing.mdx, src/content/articles/void-returning-function-assignability.mdx, src/content/articles/why-increase-your-tsconfig-target.mdx, src/content/articles/why-typescript-doesnt-follow-strict-semantic-versioning.mdx, src/content/articles/why-typescript-doesnt-include-a-throws-keyword.mdx
=> feat: switch from Twitter to Bluesky
