LearningTypeScript/site

.gitmodules
.vscode/launch.json
README.md
docusaurus.config.js
src/content/projects/10_generics.mdx
src/content/projects/11_declaration_files.mdx
src/content/projects/12_using_ide_features.mdx
src/content/projects/13_configuration_options.mdx
src/content/projects/14_syntax_extensions.mdx
src/content/projects/15_type_operations.mdx
src/content/projects/1_from_javascript_to_typescript.mdx
src/content/projects/2_the_type_system.mdx
src/content/projects/3_unions_and_literals.mdx
src/content/projects/4_objects.mdx
src/content/projects/5_functions.mdx
src/content/projects/6_arrays.mdx
src/content/projects/7_interfaces.mdx
src/content/projects/8_classes.mdx
src/content/projects/9_type_modifiers.mdx

Corresponds to https://github.com/LearningTypeScript/projects/issues/56.

Added projects repository as a submodule

---

docusaurus.config.js
src/theme/Footer/index.tsx

Update GitHub and Twitter links

---

docusaurus.config.js
package.json
src/plugins/external-project-links.js
yarn.lock

Continues #6. Pulls in https://github.com/LearningTypeScript/projects/pull/58.

Wrote a remark plugin to massage project README.mds

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/DEVELOPMENT.md
.github/FUNDING.yml
.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/01-typo.yaml
.github/ISSUE_TEMPLATE/02-bug.yaml
.github/ISSUE_TEMPLATE/03-tooling.yaml
.github/ISSUE_TEMPLATE/04-documentation.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md
README.md

🔨 chore: start on .github directory

---

src/theme/BookLink.tsx
src/theme/Footer/index.tsx
src/theme/OutlineLink/index.tsx

adds target="_blank" to external links on homepage, footer, etc.

:bug: fix: add target _blank for external links

---

src/content/articles/book-references.mdx
src/content/articles/example.mdx
src/content/articles/other.mdx

Adds what I think will be a great first article: documenting the almost 150 not-hidden references in the book.

✨ feat: add article: References in the Learning TypeScript Book

---

docusaurus.config.js
package.json
src/pages/projects/index.tsx
src/theme/Card/index.tsx
src/theme/ChapterProjects/index.tsx
src/theme/ChapterProjects/styles.module.css
src/theme/ProjectsSection/index.tsx
src/utils/useChapters.ts
yarn.lock

Reads files from disk in `docusaurus.config.js` to accumulate a big object of all the projects.

✨ feat: made chapter data dynamic with Docusaurus customFields

---

docusaurus.config.js
src/content/articles/book-references.mdx
src/theme/ArticlesSection/index.tsx
src/utils/useArticles.ts

Very similar to #42, but for articles.

✨ feat: made article data dynamic with Docusaurus customFields

---

src/css/custom.css

Adds a non-color indicator that they're links.

🐛 fix: added underline to anchors for accessibility

---

.github/ISSUE_TEMPLATE/config.yml

Directs folks with questions over to the TypeScript Discord or to me on Twitter. I don't have anything more dedicated than those.

📝 docs: add help links to issue reporting

---

src/css/custom.css
src/pages/starters/styles.module.css
src/pages/styles.module.css
src/theme/AboutTheAuthor/index.tsx
src/theme/Card/styles.module.css
src/theme/Footer/index.tsx
src/theme/Footer/styles.module.css
src/theme/HeroSection/styles.module.css
src/theme/MainArea/styles.module.css
src/theme/OutlineLink/styles.module.css
src/theme/ProjectsSection/styles.module.css
src/theme/ReadTheBook/styles.module.css

Generally finishes getting the site working per Figma designs.

✨ feat: adjusted UI per site designs

---

docusaurus.config.js

✨ feat: throw on broken links

---

docusaurus.config.js
src/clientModules.js

`clientModules` was easier than writing a plugin.

✨ feat: added Konamimojisplosion

---

docusaurus.config.js
src/theme/NavbarItem/ComponentTypes.js
src/theme/NavbarItem/DropdownLinkItem/index.tsx
src/theme/NavbarItem/DropdownLinkItem/styles.module.css

✨ feat: added shops dropdown to The Book

---

docusaurus.config.js
src/theme/ReadTheBook/styles.module.css

The main difference is that code blocks are bolder now.

✨ feat: trimmed used font weights

---

src/content/articles/extreme-explorations-of-typescripts-type-system.mdx

feat: add HypeScript to Extreme Explorations article

---

docusaurus.config.js
package.json
src/content/articles/void-returning-function-assignability.mdx
src/css/custom.css
yarn.lock

Brings in shiki-twoslash and uses it in the only existing code article.

✨ feat: add shiki-twoslash for articles

---

src/content/articles/objects-functions-and-type-narrowing.mdx
src/content/articles/objects-narrowed-before-usage.mdx

✨ feat: article: Objects Narrowed Before Usage

---

.husky/pre-commit
babel.config.js
package.json
src/theme/OutlineLink/index.tsx
yarn.lock

Formats any straggler files too.

chore: run Prettier on Git commit

---

docusaurus.config.js
src/content/articles/objects-functions-and-type-narrowing.mdx
src/pages/index.tsx
src/pages/projects/index.tsx
src/pages/starters/index.tsx
src/theme/StandardMetadata.tsx

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>

[WIP] fix: corrected <meta> tags per-page

---

package.json
src/content/articles/the-satisfies-operator.mdx
src/theme/AboutTheAuthor/index.tsx
src/theme/BlogPostItem/Header/Title/index.js
src/theme/BlogPostItem/Header/Title/styles.module.css
src/theme/BlogSidebar/index.js
src/theme/BookLinkAnchor/index.tsx
yarn.lock

Explains `satisfies`, both in general and in the specific context of next.js.

feat: add The Satisfies Operator article

---

src/pages/projects/index.tsx
src/pages/projects/styles.module.css
src/plugins/external-project-links.js

Explicitly mentions prerequisites on `/projects`. And also mentions what directory to be in for each project more explicitly.

Explained project directories and prerequisites

---

docusaurus.config.js
src/content/articles/why-typescript-doesnt-follow-strict-semantic-versioning.mdx
src/theme/CaptionedImage/index.tsx
src/theme/CaptionedImage/styles.module.css

Also adds a `CaptionedImage` component for the xckd comic within.

feat: added Why TypeScript Doesn't Follow Strict Semantic Versioning article

---

src/content/articles/narrowing-function-parameters-with-rests-and-tuples.mdx

Following up on https://twitter.com/EmilVanGalen/status/1719622053769216013.

Added mention of named tuple elements to rest tuple article

---

src/content/articles/extreme-explorations-of-typescripts-type-system.mdx

References the very fun https://github.com/psea/typescript-typelevel-binary-arithmetic by @psea.

feat: add Binary Arithmetic and Sorting to Extreme Explorations article

---

yarn.lock

Does what the issue suggests. I ran `yarn start` locally and didn't see anything different about the site.

chore: ran npx yarn-deduplicate

---

.github/renovate.json

ci: use Renovate to auto-update dependencies

---

src/css/custom.css

Fixes contrast color issue on active navigation in dark mode.
Closes #127 ✅

fix: resolve dark mode active navbar link contrast

---

src/theme/ProjectsSection/index.tsx

Corrects the incorrect project data used in the homepage.

fix: correct broken homepage The Narrow Trail link

---

src/content/articles/branded-types.mdx

Add an actual assertion function example (the one you had wasn't a [typescript assertion function](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions))

Add assertion function example

---

src/content/articles/comment-directives.mdx
src/css/custom.css

feat: article on comment directives
